// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type Post = Collections['posts']['schema']['_output']
export declare const posts: Post[]

export type Series = Collections['series']['schema']['_output']
export declare const series: Series[]

export type Chapter = Collections['chapters']['schema']['_output']
export declare const chapters: Chapter[]
